name: PR TEST

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repo source code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install python dependency
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-testmon flake8 black
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Runs a set of commands using the runners shell
      - name: Linting [flake8]
        run: |
          flake8 . --count --ignore=F403,F401,E241,E222,E251,E203,E266,F405

      - name: Run Pytest
        run: |
          pytest ./tests
